# Generated by Django 4.1.4 on 2022-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fed', models.BooleanField()),
                ('today', models.DateTimeField()),
            ],
        ),
    ]
