version: "1.0"
services:
  web:
    build: ./app
    ports:
      - 3030:3030
    command: python manage.py runserver 0.0.0.0:3030
    volumes:
      - ./app:/usr/src/app  
    env_file:
      - ./.venv.dev

